In [1]:
import pandas as pd
import numpy as np


In [17]:
m=pd.read_csv('sample3.csv',index_col=None,header=None)
m=m.values
print(m)

n=m.flatten()
print(n)

[[0 9 0 3 0 0 0 0 0]
 [0 0 0 0 2 9 0 0 1]
 [6 0 0 0 0 0 0 0 7]
 [0 7 0 0 0 0 0 1 0]
 [5 0 0 0 0 0 0 6 4]
 [0 0 0 8 0 4 0 0 9]
 [0 1 0 2 0 0 6 0 0]
 [7 8 0 0 9 0 0 0 0]
 [0 0 4 0 5 0 0 0 3]]
[0 9 0 3 0 0 0 0 0 0 0 0 0 2 9 0 0 1 6 0 0 0 0 0 0 0 7 0 7 0 0 0 0 0 1 0 5
 0 0 0 0 0 0 6 4 0 0 0 8 0 4 0 0 9 0 1 0 2 0 0 6 0 0 7 8 0 0 9 0 0 0 0 0 0
 4 0 5 0 0 0 3]


In [ ]:
[[8 0 0 0 0 0 0 0 0]
 [0 0 3 6 0 0 0 0 0]
 [0 7 0 0 9 0 2 0 0]
 [0 5 0 0 0 7 0 0 0]
 [0 0 0 0 4 5 7 0 0]
 [7 0 7 1 0 0 0 3 0]
 [0 0 1 0 0 0 0 6 8]
 [0 0 8 5 0 0 0 1 0]
 [0 9 0 0 0 0 4 0 0]]
[[8 0 0 0 0 0 0 0 0]
 [0 0 3 6 0 0 0 0 0]
 [0 7 0 0 9 0 2 0 0]
 [0 5 0 0 0 7 0 0 0]
 [0 0 0 0 4 5 7 0 0]
 [0 0 0 1 0 0 0 3 0]
 [0 0 1 0 0 0 0 6 8]
 [0 0 8 5 0 0 0 1 0]
 [0 9 0 0 0 0 4 0 0]]

In [3]:
def para(i):
    r=i//9
    c=i%9
    rr=r//3
    cr=c//3
    rr_d=rr*3
    rr_u=rr*3+3
    cr_d=cr*3
    cr_u=cr*3+3
    return r,c,rr_d,rr_u,cr_d,cr_u

print(para(45))

(5, 0, 3, 6, 0, 3)


In [4]:
def ql(m,i):
    f_l=[0,1,2,3,4,5,6,7,8,9]
    r,c,rr_d,rr_u,cr_d,cr_u=para(i)
    a=list(set(list(m[r])+list(m[:,c])+list(m[rr_d:rr_u,cr_d:cr_u].flatten())))
    q_l=[x for x in f_l if x not in a]
    return q_l,r,c

In [5]:
# 递归循环

def dg(m,n,i,l,flag):
    if flag==0:
        for j in range(i,l+1):
            if n[j]==0:
                break
        q_l,r,c=ql(m,j)
        
        if len(q_l)==0:

            flag=-1
            return flag
        if j==l and len(q_l)>1:
            flag=-1
            return flag
        for t in q_l:
            m[r,c]=t
            k=j+1
            if k==l+1:
                flag=1
                return flag
            else:
                flag=0
                flag=dg(m,n,k,l,flag)
                if flag==1:
                    break
        if flag==-1:
            m[r,c]=0
            return flag
        if flag==1:
            return flag
      


In [6]:
# 唯一法填空

def wy(m,n,l): 
    flag=0
    for i in range(l+1):
        if n[i]==0:
            q_l,r,c=ql(m,i)
            if len(q_l)==1:
                m[r,c]=q_l[0]
                n[i]=q_l[0]
                flag=1
    return m,n,flag




In [24]:
# q_l唯一值填空

# 生成全部字典
dql={}
for i in range(81):
    if n[i]==0:
        q_l,r,c=ql(m,i)
        dql[i]=q_l



[1, 2, 4, 8, 1, 2, 5, 7, 8, 1, 4, 6, 7, 8, 1, 5, 6, 7, 8, 2, 4, 5, 8, 2, 4, 5, 8, 2, 5, 6, 8]
[3, 4, 8, 3, 4, 5, 3, 5, 7, 8, 4, 5, 6, 7, 3, 4, 5, 8, 3, 4, 5, 8]
[2, 3, 4, 5, 1, 2, 3, 5, 8, 1, 4, 5, 1, 4, 8, 1, 5, 8, 2, 3, 4, 5, 8, 9, 2, 3, 4, 5, 8, 9]
[2, 3, 4, 8, 9, 2, 3, 6, 8, 9, 5, 6, 9, 3, 6, 2, 3, 5, 6, 2, 3, 5, 8, 2, 5, 8]
[2, 3, 1, 2, 3, 8, 9, 1, 7, 9, 1, 3, 7, 1, 2, 3, 7, 2, 3, 7, 8]
[1, 2, 3, 2, 3, 6, 1, 2, 3, 6, 1, 3, 6, 7, 2, 3, 5, 7, 2, 3, 5, 7]
[3, 9, 3, 5, 9, 3, 4, 7, 8, 3, 7, 8, 4, 5, 7, 8, 9, 5, 8]
[2, 3, 5, 6, 1, 4, 6, 1, 3, 6, 1, 2, 4, 5, 2, 4, 5, 2, 5]
[2, 9, 2, 6, 1, 6, 7, 1, 6, 7, 8, 1, 2, 7, 8, 9, 2, 7, 8, 9]


In [7]:
from collections import Counter
#横向比对
def h_c(m,n):
    flag=0
    dql=dq_l(m,n)
    for i in range(9):
        la=[]
        k_l=[x for x in range(9*i,9*i+9) if x in dql.keys()]
        for k in k_l:
            la+=dql[k]
        ct=Counter(la)
        lb=[]
        
        for j,v in ct.items():
            if v==1:
                lb.append(j)
        for t in lb:
#         if len(lb)>0:
#             t=lb[0]
            for k in k_l:
                if t in dql[k]:
                    r,c,_,_,_,_=para(k)
                    n[k]=t
                    m[r,c]=t
#                     print('hc',k,r,c)
                    k_l.remove(k)
                    flag=1
                    break
            
#     print(m)
    dql={}
    return m,n,flag
    
#纵向比对
def v_c(m,n):
    flag=0
    dql=dq_l(m,n)
    for i in range(9):
        la=[]
        k_l=[x for x in range(i,73+i,9) if x in dql.keys()]
#         print(k_l)
        for k in k_l:
            la+=dql[k]
        ct=Counter(la)
#         print(k_l)
        lb=[]
        for j,v in ct.items():
            if v==1:
                lb.append(j)
        for t in lb:
#         if len(lb)>0:
#             t=lb[0]
#             print(lb)
            for k in k_l:
                if t in dql[k]:
                    
                    r,c,_,_,_,_=para(k)
                    n[k]=t
                    m[r,c]=t
#                     print('vc',k,r,c)
#                     print('bvc:',k_l)
                    k_l.remove(k)
#                     print('avc:',k_l)
                    flag=1
                    break            
#     print(m)
    dql={}
    return m,n,flag

#九宫格对比

def n_c(m,n):
    flag=0
    dql=dq_l(m,n)
    c_l=[x for x in range(0,9,3)]+[x for x in range(27,36,3)]+[x for x in range(54,63,3)]
    for i in range(9):
        la=[]
        u=c_l[i]
        n_l=[x for x in range(u,u+3)]+[x for x in range(u+9,u+12)]+[x for x in range(u+18,u+21)]
        k_l=[x for x in n_l if x in dql.keys()]
        for k in k_l:
            la+=dql[k]
        ct=Counter(la)
        lb=[]
        for j,v in ct.items():
            if v==1:
                lb.append(j)
        for t in lb:
#         if len(lb)>0:
#             t=lb[0]
            for k in k_l:
                if t in dql[k]:
                    r,c,_,_,_,_=para(k)
                    n[k]=t
                    m[r,c]=t
#                     print('nc',k,r,c)
                    k_l.remove(k)
                    flag=1
                    break     
#     print(m)
    dql={}
    return m,n,flag

In [8]:
def dq_l(m,n):
    dql={}
    for i in range(81):
        if n[i]==0:
            q_l,r,c=ql(m,i)
            dql[i]=q_l
    return dql

In [9]:
def sd2(m,n):

    flag=1
    while flag==1:
        
        m,n,flag=h_c(m,n)
        m,n,flag=v_c(m,n)
        m,n,flag=n_c(m,n)
    
#     print(m,n)
    for i in reversed(range(1,81)):
        if n[i]==0:
            l=i
            break
    i=0
    flag=0
    flag=dg(m,n,i,l,flag)
    
    return m

In [56]:
nl=[x for x in range(0,9,3)]+[x for x in range(27,36,3)]+[x for x in range(54,63,3)]
t=nl[0]
n_l=[x for x in range(t,t+3)]+[x for x in range(t+9,t+12)]+[x for x in range(t+18,t+21)]


print(len(dql))

57


In [10]:
def sd(m,n):
    for i in reversed(range(1,81)):
        if n[i]==0:
            l=i
            break
    
    flag=1
    while flag==1:
        m,n,flag=wy(m,n,l)
    flag=0
    i=0
    flag=dg(m,n,i,l,flag)
    return m

In [19]:
import time
starttime=time.time()
i=0
flag=0
m2=np.array(m)
n2=np.array(n)
m_f=sd2(m2,n2)
ut=time.time()-starttime
print(m_f,ut)

[[8 9 1 3 4 7 2 5 6]
 [3 5 7 6 2 9 4 8 1]
 [6 4 2 5 8 1 9 3 7]
 [4 7 8 9 6 5 3 1 2]
 [5 3 9 7 1 2 8 6 4]
 [1 2 6 8 3 4 5 7 9]
 [9 1 5 2 7 3 6 4 8]
 [7 8 3 4 9 6 1 2 5]
 [2 6 4 1 5 8 7 9 3]] 2.742000102996826


In [60]:
[[8 9 1 3 4 7 2 5 6]
 [3 5 7 6 2 9 4 8 1]
 [6 4 2 5 8 1 9 3 7]
 [4 7 8 9 6 5 3 1 2]
 [5 3 9 7 1 2 8 6 4]
 [1 2 6 8 3 4 5 7 9]
 [9 1 5 2 7 3 6 4 8]
 [7 8 3 4 9 6 1 2 5]
 [2 6 4 1 5 8 7 9 3]] 

4
3
2
1
